### ISSUE TITLE
Thanks your articles and I have found something can make it better

### ISSUE THREAD

**Issue by shynome** [cmizzi/p1ngouin.com#6]
Thanks for your great article: https://p1ngouin.com/posts/how-to-manage-iptables-rules-with-ufw-and-docker
I make ufw work with docker by follow this article, and found something can make it better

> Now you have to tell the firewall that the rules defined by UFW must be executed before those of Docker. Let's add these lines to the /etc/ufw/after.init file.

I think the file path should be `/etc/ufw/after.rules`

And by default `/etc/ufw/before.init` is not executable, adding some tips about that can save time for those who are new to ufw

at last, thanks for your great article again

**Comment by cmizzi** [comment]
Great catch ! I'll update the article soon :+1:

**Comment by teutat3s** [comment]
+1 came across the same things

Thanks for the article!
